import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Slab } from "next/font/google";
import "./globals.css";
import { MeProvider } from "@/providers/Me";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Roboto_Slab({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: "600"
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          background: "linear-gradient(-225deg, #E3FDF5 0%, #FFE6FA 100%)"
        }}
      >
        <MeProvider>
          <div className="w-full h-full items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-mono)]">
            <div className="w-full max-w-[450px] sm:w-[400px] sm:h-[650px] rounded-[24px] flex justify-center glass overflow-y-scroll">
              {children}          
            </div>
          </div>
        </MeProvider>
      </body>
    </html>
  );
}
